apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cms-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: cms-sa
    namespace: toqqer-test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
