apiVersion: v1
kind: PersistentVolume
metadata:
  name: toqqer-test-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/toqqer-test
